### ISSUE TITLE
Reestruturação pacote python

### ISSUE THREAD

**Issue by FelipeSBarros** [FelipeSBarros/crossfire#2]
Tendo visto a [tualização da API do Fogo Cruzado](https://github.com/FelipeSBarros/crossfire/discussions/1#discussion-5568660), decidi rever esse pacote.
Além da necessidade de atualizar `endpoints`, vi que sería possível fazer algumas melhorias...
Conversnado com o @cuducos, pensamos em:

- [x] Renomear módulos para simplificar o pacote (evitar redundância)<br>#30
- [x] [Reestruturar o código](https://github.com/FelipeSBarros/crossfire/discussions/1#discussioncomment-6869175) melhorando o processo de `longing` da API;
    - [x] (Re)escrever método para [endpoint states](https://api.fogocruzado.org.br/docs/endpoint/states) <br> #24 
    - [X] (Re)escrever método para [endpoint cities](https://api.fogocruzado.org.br/docs/endpoint/cities) <br> #29 
    - [x]  (Re)escrever método para [endpoint occurrences](https://api.fogocruzado.org.br/docs/endpoint/occurrences) <br> #31 
    - [x] Possibilidade de sobreescrever as variáveis de ambiente ao usar o Client()<br> #19 
    - [x] remover `get_cities`<br> #18 
    - [X] Método de atualizazção de token (que possuem uma duração de uma hora);
- [x] Separar o pacote R do Python; <br> #62
- [x] Escrever documentação<br> #27 
- [x] Atualizar testes<br> #9 
- [x] Adicionar [githubActions](https://github.com/features/actions)<br> #16 
    - [x] Black
    - [x] Ruff
    - [x] Testes

**Comment by cuducos** [comment]
Acredito que o mais fácil para começar seja pelas ferramentes de automação de testes, formatação etc.

Depois, GitHub Actions para que isso rode automático em cada PR.

Aí podemos seguir o resto com TDD e verificação automática : )

**Comment by FelipeSBarros** [comment]
Tive um tempinho hj...
Não sei se era o que vc tinha recomendado, mas pude fazer um [commit](https://github.com/FelipeSBarros/crossfire/commit/52ad07f0437bce6acdd66ed18cdae910670a1be6) com o seguinte:
- Criar un novo branch;
- Remover o poetry_lock que estava perdido na raiz do repo, mas fora da estrutura do pacote;
- Criei um .github/workflows/black.yml
    - [Segui a sugestão](https://black.readthedocs.io/en/stable/integrations/github_actions.html) de adicionar o `--check` e adicionei o `--verbose` tbm;
    - apliquei o  black para deixar módulos já com o code style a ser validado;
 
Agora quero ver se eu consigo colocar o UnitTest para rodar ou, quem sabe, já passar converter os testes ao pytest.
Vou avisando por aqui...

**Comment by cuducos** [comment]
Dica: se você precisa listar as coisas que um commit faz, vc fez muita coisa em um único commit.

Cada commit tem que ser atômico, fazer uma coisa bem específica e precisa.

Você pode juntar pequenas coisas dessas em uma branch, e com cada branch abrir um PR para coletar comentários e aprovação para fazer o _merge_.

Da lista q vc fez acho que dá para separar o avanço em três PR (ou seja, três branchs, cada um com alguns commits):

- limpeza (excluir coisas não utilizadas): uma branch com três commits (um excluindo testes não utilizados, outro excluindo o módulo não utilizado, outro excluindo o arquivo extra do Poetry)
- outro branch para aa coisas do GitHub Action
- e outro para adicionar o `pytest` **e** testes e documentação utilizando o novo pacote


Pq isso?

1. Pense em commits como unidades reversíveis de trabalho. Imagine que a gente volte a utilizar o `get_cities.py`; eu tenho como fazer um `git revert HASH DO COMMIT` e voltar esse arquivo (sem voltar os demais que estavam na limpeza)
2. Pense em PR como funcionalidades completas, isso dá um contexto de tamanho ideal para revisão e conversa específica sobre a implementação

**Comment by FelipeSBarros** [comment]
Legal, @cuducos . Estrei atento a isso. Eu, na verdade pensei ao contrŕio... tinha feito vários commits e no fim fiz um squash...
Por algum motivo achei que ler vários commits seria mais "dificil" (chato?).
Vou considerar para os próximos.

Seguem alguma dúvidas:
Posso fazer um fork do meu fork? para poder abrir PRs diferentes...

Sobre Teste:
Estou entendendo que é isso: vamos tratar o `UndefinedValueError`, caso o usuário não tenha configurado o `.env` ou `settings.ini`;
Com isso, pensei em tres cenários de teste:

```
# teste_settings.py
from crossfire.settings import Settings
from unittest.mock import patch
import pytest
from decouple import UndefinedValueError
```

1. Usuário com `.env` configurado corretamente:
Para este caso, estive pesquisando uma forma de não ter que fazer o commit do meu `.env`. Ví que o `pytest-env` cuida disso para o testes. Então adicionei ao pacote e creiei um `pytest.ini` na pasta do projeto com as variáveis de ambiente, conforme esperado
```
class TestSettings:
    def test_settings_init_with_dotenv(self):
        settings = Settings()
        assert settings.email
        assert settings.password
```

2. Usuário com `.env` configurado mas subreescrevendo as variáveis de ambiente ao passar-las pela instanciação da classe:
```
class TestSettings:
    ...
    def test_settings_init_by_parameter(self):
        settings = Settings(email="test@gmail.com", password="pass")
        assert settings.email == "test@gmail.com"
        assert settings.password == "pass"
```

**Fazem sentido esses testes?**

E agora estive pensando em como testar a terceira situação:

3. Quando o usuário não possui as variáveis de ambiente configuradas e o erro `UndefinedValueError` é levantado...
Vi algumas possibilidades na internet, como essa:
```
@pytest.fixture(autouse=True, scope="function")
def unset_env_variables(monkeypatch):
    # Simula a ausência das variáveis de ambiente
    monkeypatch.delenv("FOGOCRUZADO_EMAIL", raising=False)
    monkeypatch.delenv("FOGOCRUZADO_PASSWORD", raising=False)


def test_settings_without_env_variables():
    with pytest.raises(Exception, match=SETTINGS_ERROR_MESSAGE):
        settings = Settings()
```
Mas parece que o Settings não está levantando a exception...

Alguma indicação por onde ir?

**Comment by cuducos** [comment]
> Vou considerar para os próximos.

Para os próximos? E como você pensa em pegar feedback para trazer esses commits para a branch principal então?

> Posso fazer um fork do meu fork? para poder abrir PRs diferentes...

Eu não entendi a pergunta. Me parece um [problema XY](https://pt.m.wikipedia.org/wiki/Problema_XY). Olhando a mensagem que abre essa issue, ela tem uma lista de coisas a serem feitas. 

Cada coisa dessa pode ser feita em um branch. E cada branch vira um PR para branch principal desse único fork teu.

> Mas parece que o Settings não está levantando a exception...

Não conheço esse `monkeypatch` teria que estudar o q q esse objeto faz. 

> acabei subindo as ultimas modificações sem PR, mesmo.

Tu não quer code review? Eu tava contando que era assim que tu queria minha ajuda : ( Que tristeza.

**Comment by FelipeSBarros** [comment]
> Para os próximos? E como você pensa em pegar feedback para trazer esses commits para a branch principal então?

Perdão. Vou fazer o revert e rever os commits, e ir organizando em branches e PR separados.

> Eu não entendi a pergunta. Me parece um [problema XY](https://pt.m.wikipedia.org/wiki/Problema_XY). Olhando a mensagem que abre essa issue, ela tem uma lista de coisas a serem feitas.

Ok, estarei a tento a não perguntar por Y, quando necessito X.

>  E cada branch vira um PR para branch principal desse único fork teu.

Estava entendendo que um PR se realiza entre repos diferentes (repo original e um fork dele), Nao entre branches de um mesmo repo, ainda mais sendo este repo um fork. Mas vou dar uma olhada como fazer esses PR entre branches do meu repo...

> Tu não quer code review? Eu tava contando que era assim que tu queria minha ajuda : ( Que tristeza.

Quero, sim! Vou refazer tudo... talvez demore um pouco. Mas o farei.

**Comment by cuducos** [comment]
> Estava entendendo que um PR se realiza entre repos diferentes (repo original e um fork dele), Nao entre branches de um mesmo repo

PR é uma UI para fazer um `git merge` — isso significa lecar código de uma branch para outra (seja de um mesmo repositório ou não).

> Tipo, ao adicionar refactor, todos deverão ter o nome refactor*? Seria isso?

Isso acho desnecessário. O que precisa é não permitir `git push` direto para a `master` branch.

Ou seja:
* Padrão de nome de branch para qual vale a regra: `master`
* ✅ na opção _Require a pull request before merging_
* ✅ na opção _Require approvals_ se quiser tornar obrigatório ter _code review_ aprovando antes de fazer o _merge_ (recomendo)

**Comment by FelipeSBarros** [comment]
> Padrão de nome de branch para qual vale a regra: master

Perfeito. Agora entendi.
Feito.

**Comment by cuducos** [comment]
Minha sugestão de próximos passos:

1. crie um branch para o Black, q vc mencionou que já tinha feito/estava fazendo.
2. abra um PR (pode ser como rascunho, se tiver ainda muitas perguntas)
3. aí falamos da implementação no PR
4. com a conversa, você vai fazendo `git push` de mais commits para essa branch (o que atualiza o PR)
5. quando estiver, OK, o PR é aprovado e vc clica em _Merge_ para o código ir para a `master`

Aí é de ti e de quem cuida do repo principal ver como/quando mandamos um PR daqui pra lá:
1. se pouco a pouco, como proponho aqui,
2. ou se prefereferem um PRzão com a nova versão

Se for a opção 1, o fluxo seria:
- branch de trabalho no teu repositório
- PR sugeringo a incorporação da tua branch (no teu repositório) direto na `master` do repo principal `voltdatalab/crossfire`
- quando eles mergearem, aí vc puxa as alterações manualmente para a `master` do teu _fork_

**Comment by FelipeSBarros** [comment]
> [ ] [Reestruturar o código](https://github.com/FelipeSBarros/crossfire/discussions/1#discussioncomment-6869175) melhorando o processo de `longing` da API;
> * [ ]  (Re)escrever método para [endpoint states](https://api.fogocruzado.org.br/docs/endpoint/states)
> * [ ]  (Re)escrever método para [endpoint cities](https://api.fogocruzado.org.br/docs/endpoint/cities)
> * [ ]   (Re)escrever método para [endpoint occurrences](https://api.fogocruzado.org.br/docs/endpoint/occurrences)

@cuducos dei uma organizada aqui no que ainda falta, principalmente em termos de interação com a API.
Veja se falta alguma coisa.
Seguirei outro dia...

**Comment by cuducos** [comment]
Já que **não** começamos reescrevendo a documentação, precisamos atualiza-la em algum monento…

**Comment by FelipeSBarros** [comment]
> - [ ] Escrever documentação
Adicionado à lista

**Comment by cuducos** [comment]
Estava pensando… o pacote pode ter `pandas` como uma dependência opcional.

Em muitos projetos não se usa o Pandas, e a gente pode ter algo como:

* `pip install crossfire` que não instala o Pandas e retorna os dados como dicionários
* `pip install crossfire[df]` que instala o Pandas e retorna os dados como `DataFrame`
* `pip install crossfire[geo]` que instala o GeoPandas e retorna os dados como `GeoDataFrame` ou `DataFrame` (dependendo do _endpoint_)

**Comment by FelipeSBarros** [comment]
Perfeito. Estou de acordo.
Entendo que a ideia do pacote é permitir que as pessoas acessem os dados. Depois elas posem transformá-los, usá-los como quiserem.

**Comment by cuducos** [comment]
Por mim, sim. Tanto que foi o que sugeri em #27.

**Comment by FelipeSBarros** [comment]
Legal, eu não lembrava do seu comentário. Vou ver se começo a trabalhar nisso hoje à tarde.

**Comment by FelipeSBarros** [comment]
@cuducos , obrigado pela paciencia e ajuda nesse trabalho!
Vou revisar se faltou alguma coisa. Caso vc identifique alguma coisa faltando, só falar.

**Comment by FelipeSBarros** [comment]
@cuducos , sobre a publicação do pacote... na verdade sobre a versão: atualmente a versão que consta é 0.2.0.2. òbvio que não dei  a atenção a isso antes, por isso desse valor que, talvez faça pouco sentido.
Entendo que a nova versão é um cambio significativo, pois sem essa versão não haverá como acessar a API.
Você teria alguma sugestão sobre os números da nova versão?
`0.3.0` ou `0.3.0.0`
ou `1.0.0`?

**Comment by FelipeSBarros** [comment]
> [Estamos mudando a API, então penso que é uma _major_](https://semver.org/). Voto em 1.0.0.

Vou com o seu voto.

Estava lembrando aqui que o git tem um sistema de [tags](https://git-scm.com/book/en/v2/Git-Basics-Tagging). Você já usou? Acha importante usar isso para marcar a versão do módulo?

**Comment by FelipeSBarros** [comment]
> > Estava lembrando aqui que o git tem um sistema de [tags](https://git-scm.com/book/en/v2/Git-Basics-Tagging).
> 
> Eu não gosto e só uso quando absolutamente necessário (por exemplo, em outras linguagens, o repositório oficial de pacotes lê a versão da tag no GitHub; o que não é caso do Python). Pq eu não gosto? Pq aí vc tem o número da versão em dois lugares (no `pyproject.toml` e na tag). E eventualmente pode esquecer de atualizar um sem atualizar outro e fica desalinhado etc…

Faz sentido. Vou seguir com o versionamento do `pyproject.toml`, para simplificar...
